(package "marquee-header"
         "0.0.9"
         "Code interface for displaying marquee in header")

(website-url "https://github.com/jcs-elpa/marquee-header")
(keywords "wp" "animation" "marquee")

(package-file "marquee-header.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
